language: "ko-KR"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  finishing_touches:
    unit_tests:
      enabled: false
chat:
  auto_reply: true
