spring:
  datasource:
    url: jdbc:h2:mem:shortlink
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  url: ${SERVER_URL:http://localhost:8080}
  port: 8080

logging:
  level:
    io.github.columnwise.shortlink: DEBUG
    org.springframework.data.redis: DEBUG