spring:
  application:
    name: ShortLink

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

server:
  url: ${SERVER_URL:http://localhost:8080}