spring.application.name=events-consumer
# 입력 토픽 (기본값 link_hits)
app.stream.input.linkHits=link_hits

# Kafka 역직렬화 기본 타입(도메인 이벤트)
spring.kafka.consumer.properties.spring.json.trusted.packages=io.columnwise.shortlink.*
spring.kafka.consumer.properties.spring.json.value.default.type=io.columnwise.shortlink.eventsconsumer.domain.event.VisitEvent

# 컨슈머 기본 그룹 ID
spring.kafka.consumer.group-id=shortlink-events-consumer
